model:
  name:  "tiiuae/falcon-mamba-7b-instruct" #"meta-llama/Meta-Llama-3.1-8B-Instruct" # "tiiuae/falcon-mamba-7b-instruct" # "meta-llama/Meta-Llama-3.1-8B-Instruct" # "Qwen/Qwen2.5-7B-Instruct"
#"mistralai/Mistral-7B-Instruct-v0.3" #"meta-llama/Llama-3.2-3B-Instruct"
data:
  file_path: "data/processed/edu_test_updated.csv"
prompt:
  option: 1
  definitions: False
  examples: False
  fallacy_classes: 1 #FINE_GRAINED = 1 # COPI = 2 # ARISTOTLE = 3
