model:
  name: "mistralai/Mistral-7B-Instruct-v0.3" #"meta-llama/Llama-3.2-3B-Instruct"
data:
  file_path: "data/processed/edu_test_updated.csv"
prompt:
  definitions: True
  examples: False
  coarse_grained_classification: False
